### ISSUE TITLE
Resize that icon!

### ISSUE THREAD

**Issue by K0-RR** [LimeShulkerBox/better-sodium-video-settings#11]
This mod icon is huge and takes insane storage space compared to the code. You should downscale it and maybe losslessly compress it with Leanify or Oxipng. Can open a PR with a 256x256 icon for you.

**Comment by piemanau** [comment]
Hey! I can probably do this but I will forgot, can you make a pr? Thanks!

**Comment by piemanau** [comment]
Fixed in #19
