### ISSUE TITLE
Missing show fps?

### ISSUE THREAD

**Issue by Ozakinn** [LimeShulkerBox/better-sodium-video-settings#15]
sodium had this feature, but when i added this mod its gone or did i just not see it.

**Comment by piemanau** [comment]
Hey! Thanks for the issue report but could I have the versions of the mods you were using? Thanks!

**Comment by Ozakinn** [comment]
Found it. its my problem, another mod called "sodium extra" gives more settings for sodium. (fps, particles, fogs and more)
You can add this features in the mod.

**Comment by piemanau** [comment]
All good :)
