### ISSUE TITLE
[Suggestion] Lists?

### ISSUE THREAD

**Issue by RaptaG** [LimeShulkerBox/better-sodium-video-settings#16]
When using OptiFine, all options are sorted on lists.. I love your mod, but the lists is veryy long!

**Comment by piemanau** [comment]
Wym? This isn't compatible with optifone because it requires sodium and they don't work together

**Comment by RaptaG** [comment]
What I mean is if you could sort the video options in lists, like with the optifine video settings, not run it together with optifine

**Comment by RaptaG** [comment]
Like for example an "Animations...." button with the Animations options

**Comment by RaptaG** [comment]
Oh, I just noticed that the sodium's extra options aren't included in your mod , so what I said is useless since they are not supported :(
