### ISSUE TITLE
Needs 1.18.2 Update

### ISSUE THREAD

**Issue by ghost** [LimeShulkerBox/better-sodium-video-settings#17]
Sodium Video Settings Button does nothing and stays in the default video settings in 1.18.2. Most likely just needs an update

**Comment by piemanau** [comment]
What mods are you using?

**Comment by Lukebb04** [comment]
This is happening for me with [Reese's Sodium Options](https://www.curseforge.com/minecraft/mc-mods/reeses-sodium-options)

**Comment by mharbb** [comment]
Sodium 
Sodium extra
balm
client tweaks
cloth config
clumps
fabric api
ferritecore
inventory sorter
lithium
mod menu
reeeses sodium options
starlight fabric
wi zoom
xaeros minimap
xaeros worldmap

**Comment by ghost** [comment]
> What mods are you using?

Sodium
Sodium extra
balm
client tweaks
cloth config
clumps
fabric api
ferritecore
inventory sorter
lithium
mod menu
reeeses sodium options
starlight fabric
wi zoom
xaeros minimap
xaeros worldmap

**Comment by ghost** [comment]
> > What mods are you using?
> 
> Sodium Sodium extra balm client tweaks cloth config clumps fabric api ferritecore inventory sorter lithium mod menu reeeses sodium options starlight fabric wi zoom xaeros minimap xaeros worldmap

All up to date (1.18.2)

**Comment by MIOGMIOG** [comment]
> This is happening for me with [Reese's Sodium Options](https://www.curseforge.com/minecraft/mc-mods/reeses-sodium-options)

This is true, he have to fix support for Reeses sodium options.

**Comment by piemanau** [comment]
Fixed in #19

**Comment by ghost** [comment]
> Fixed in #19

How do I download this?

**Comment by piemanau** [comment]
Ah I forgot to upload to CurseForge, thank you for the reminder, I will upload it now

**Comment by ghost** [comment]
NP
