### ISSUE TITLE
Crash on 1.19.3

### ISSUE THREAD

**Issue by Reber01Good** [LimeShulkerBox/better-sodium-video-settings#29]
I used the latest version of the mod together with sodium 0.4.8 on fabric 1.19.3. The crash happens right before the main menu would load. 
Here is the log: https://pastebin.com/cZiueJN6

**Comment by piemanau** [comment]
Hmm alright, something is wrong, I will have to look at it later though, thanks for the report.

**Comment by Reber01Good** [comment]
No problem, helping mods fix their bugs is amazing!

**Comment by Reber01Good** [comment]
Also to add I saw that the mod recommands using it together with the two sodium addon mods, tried it with them too, same result.

**Comment by piemanau** [comment]
Hey there, I tried it with sodium 0.4.8 on fabric 1.19.3 and it worked fine, can I ask, do you have the 1.19.x version of bsvsb 3.0.2 or the 1.19.3 one? The 1.19.3 one works 100% fine for me, you can re-download it [here](https://www.curseforge.com/minecraft/mc-mods/better-sodium-video-settings-button/files/4151757) to use. If that still doesn't work I will get you to try with just sodium and bsvsb to see if it is a mod compat issue with other mods.

**Comment by Reber01Good** [comment]
1.19.3 from modrinth. Ok it seems the file from curseforge works, but it crashes when clicking the video settings button. This is weird since the version from modrinth is not the same as the curseforge one, you should check. Ill send the log for this new crash and ill do the fun thing of sifting through the 61 mods. Wish me luck!

https://pastebin.com/cjpGBUa0

**Comment by Reber01Good** [comment]
![image](https://user-images.githubusercontent.com/93145739/213474078-7ef7e33e-c88a-47af-9525-6d674aa06ae3.png)
Here, when clicking the 1.19.3 on the left, it brings me to a 1.19.x, that is actually for 1.19.2
So you probably got the file version mixed up, make sure to fix it :)

**Comment by Reber01Good** [comment]
Okay, found the conflicting mod pretty quick, it's betterbiomeblend. I think that is because the mod increases biome blend radius to 29x, compared to default 15, and your mod does not expect that number and causes a crash. This is pretty annoying for me since I wanted to get the large biome blend radius together with sodium, but sodium's terrible settings screen didn't allow me to change that. If you could fix it that would be really nice, but I do realise that betterbiomeblend is at fault here for not adding it's custom slider to sodium, even if it claims compatibility.

I'll stick with bsvsb since the menu is still better than sodium, and when the two mods will be compatible i'll use both.

**Comment by piemanau** [comment]
> 1.19.3 from modrinth. Ok it seems the file from curseforge works, but it crashes when clicking the video settings button. This is weird since the version from modrinth is not the same as the curseforge one, you should check. Ill send the log for this new crash and ill do the fun thing of sifting through the 61 mods. Wish me luck!
> 
> https://pastebin.com/cjpGBUa0

Could I get you to redownload the 1.19.3 one from modrinth? I am pretty sure they are exactly the same, they may not be but I looked the the jar for both and they looked pretty similar

**Comment by piemanau** [comment]
> ![image](https://user-images.githubusercontent.com/93145739/213474078-7ef7e33e-c88a-47af-9525-6d674aa06ae3.png) Here, when clicking the 1.19.3 on the left, it brings me to a 1.19.x, that is actually for 1.19.2 So you probably got the file version mixed up, make sure to fix it :)

Oh ok thats weird...

**Comment by piemanau** [comment]
I think it is because it has the same version it is messing up... Wont do that again haha

**Comment by piemanau** [comment]
> Okay, found the conflicting mod pretty quick, it's betterbiomeblend. I think that is because the mod increases biome blend radius to 29x, compared to default 15, and your mod does not expect that number and causes a crash. This is pretty annoying for me since I wanted to get the large biome blend radius together with sodium, but sodium's terrible settings screen didn't allow me to change that. If you could fix it that would be really nice, but I do realise that betterbiomeblend is at fault here for not adding it's custom slider to sodium, even if it claims compatibility.
> 
> I'll stick with bsvsb since the menu is still better than sodium, and when the two mods will be compatible i'll use both.

Thats odd... they used to be compatible, I wonder if they changed their code, I'll check it out

**Comment by piemanau** [comment]
Seems like they don't support 1.19.3 at all yet based off of this issue https://github.com/FionaTheMortal/better-biome-blend/issues/64

**Comment by Reber01Good** [comment]
[(modrinth) bsvsb-3.0.2.zip](https://github.com/piemanau/better-sodium-video-settings/files/10465798/modrinth.bsvsb-3.0.2.zip)

Now I see that it is indeed their fault, they commited the sin of making their mod 1.19.x, so they don't have to care about updating it. It may not get fixed until 1.20, but maybe the reports they are getting will wake them up. Thanks for the help, and I hope you figure out what the issue is with the modrinth file.

**Comment by piemanau** [comment]
No worries, have a good day :)

**Comment by Reber01Good** [comment]
You too!
