### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by voidrinix** [LimeShulkerBox/better-sodium-video-settings#31]
Hello, minecraft crashes at startup, here is the [log](https://mclo.gs/InhsElf)

To reproduce download my [modpack](https://modrinth.com/modpack/rinixized/version/1.1.5) and add [BSVSB](https://modrinth.com/mod/better-sodium-video-settings-button/version/hZcgUcxn) to mods folder and try to run minecraft.

**Comment by cjtganzon** [comment]
The 3.0.2 modrinth version crashes for me, 3.0.2 curseforge works though

**Comment by voidrinix** [comment]
lol, same for me. Then this isn't mod's issue, I think author uploaded wrong version to modrinth. I think the issue is figured out.

**Comment by piemanau** [comment]
I uploaded a 1.19.x 3.0.2 and a 1.19.3 version, too long ago not sure if I uploaded the correct one or not haha
