### ISSUE TITLE
Possible Incompatibilities (1.19.3)

### ISSUE THREAD

**Issue by DebZakari** [LimeShulkerBox/better-sodium-video-settings#32]
This mod crashes on my minecraft 1.19.3

**Comment by cjtganzon** [comment]
Download the curseforge file if the modrinth one doesn't work

**Comment by piemanau** [comment]
Yea for some reason the modrinth version doesn't work. I will try to fix in the future

**Comment by piemanau** [comment]
I have uploaded a 1.19.4 version which also works with .3
