### ISSUE TITLE
1.20.1

### ISSUE THREAD

**Issue by nijahplays** [LimeShulkerBox/better-sodium-video-settings#35]
Hello, what is the status on a 1.20.1 version?

**Comment by piemanau** [comment]
It should work. I haven't tested though, let me know when you test the 1.20 file :)

**Comment by nijahplays** [comment]
The problem I'm having is that since there is no release file under 1.20.1 in Modrinth, modloaders can't detect that it is installable.

**Comment by piemanau** [comment]
Ah gotcha. Just updated it give it a go now

**Comment by nijahplays** [comment]
Cam confirm it's working for 1.20.1
