### ISSUE TITLE
BSVSB not working on Sodium 0.5.8

### ISSUE THREAD

**Issue by ShadowTigerCool** [LimeShulkerBox/better-sodium-video-settings#38]
https://pastebin.com/PHC4kWPA

**Comment by SnowPowerCore** [comment]
Also doesn't work with Sodium 0.5.8: button doesn't do anything at the click.

**Comment by piemanau** [comment]
Could you try without reeses video options?

**Comment by SnowPowerCore** [comment]
Sorry, i've googled and found a way to switch to the classic menu on demand - through "Shift + P". I'll sign off from this issue.

**Comment by piemanau** [comment]
Hey, did you end up trying that anyway? Pretty sure sodium doesn't support macos anymore so I can't really test unfortunately..

**Comment by Tempest-5ky** [comment]
Gave it a shot, can confirm that the button still doesn't work when Reeses Video Options is removed!

**Comment by piemanau** [comment]
> Gave it a shot, can confirm that the button still doesn't work when Reeses Video Options is removed!

Is there any chance you could give me a log? I'm pretty sure sodium doesn't work on macOS anymore so I can't..

**Comment by Tempest-5ky** [comment]
gotchu! 
here's the latest.log with Reese's: https://mclo.gs/nFDeswv
and without: https://mclo.gs/vK8RqBo

The big error at the end is what happens when this mod's video settings button is clicked! Then 'stopping' isn't a crash it's just me quitting the game. Looks like this mod is trying to call a method that doesn't exist?

**Comment by suerion** [comment]
Had the same issue on 1.20.1, could be a issue on sodiums update

**Comment by piemanau** [comment]
I think I fixed this with the 1.20.6 and 1.21 versions, if it doesnt work, let me know. (Or if you want a back port I guess)
