### ISSUE TITLE
Sodium Video Settings button doesnt work

### ISSUE THREAD

**Issue by Ch1216** [LimeShulkerBox/better-sodium-video-settings#39]
https://github.com/piemanau/better-sodium-video-settings/assets/68875386/d6e2a0ee-fd34-432f-94c7-5760a52b6605

Turn on sound to hear me click the butotn

MInecraft Version: 1.20.4
Sodium Version: mc1.20.4-0.5.8
BSVSB Version: 3.0.4

https://pastebin.com/NxZrAsJD

**Comment by piemanau** [comment]
I believe that the 1.20.6 version fixes this issue, however the fabric.mod.json may need to be modified. If youd like it backported I may be able to get around to it at somepoint.
