### ISSUE TITLE
1.21

### ISSUE THREAD

**Issue by ghost** [LimeShulkerBox/better-sodium-video-settings#42]
1.21 support is needed now, and just changing the fabric mod json doesn't work.

**Comment by LordEnder-Kitty** [comment]
This mod hasn't been properly updated in a year. I'm borderline about to fork it and update it myself.

**Comment by ghost** [comment]
> This mod hasn't been properly updated in a year. I'm borderline about to fork it and update it myself.

Tbh please do, I would appreciate it.

**Comment by muluffel** [comment]
> This mod hasn't been properly updated in a year. I'm borderline about to fork it and update it myself.

any updates on that idea?

**Comment by BrailleBennett** [comment]
If you do, let me know. I manage a modpack for blindness accessibility mods, and cloth config isn't accessible, which means that the sodium settings menu doesn't work for screen readers. So people have to use shift+P to get to the vanilla menu every time they open the video settings menu, which some people are confused about.

**Comment by piemanau** [comment]
Apologies guys, I have been super busy recently 😬. Have been meaning to do it for a while now however been stuck doing assessments constantly for school.

**Comment by LordEnder-Kitty** [comment]
> > This mod hasn't been properly updated in a year. I'm borderline about to fork it and update it myself.
> 
> any updates on that idea?

I've been thinking about it recently. I mean, if the original guy is gonna do it soon, I'd rather not waste my time, but I would be more than happy to figure out how to update it. Maybe even add config options for the button layout.

**Comment by piemanau** [comment]
Updated
