### ISSUE TITLE
Support for sodium 1.6

### ISSUE THREAD

**Issue by BrailleBennett** [LimeShulkerBox/better-sodium-video-settings#47]
When the sodium 1.6 beta is installed, using the sodium settings button just makes a fun clicking noise and nothing happens. Although it's a fun noise maker, I would appreciate if the sodium settings opened. :) Optionally, right now, you could make it so the mod hard depends on sodium version 1.5.7 or whatever just so people don't think the whole mod is broken when they try to use 1.6.

**Comment by piemanau** [comment]
Related to #46

**Comment by piemanau** [comment]
There is a alpha version available to download now.
