### ISSUE TITLE
Add github actions

### ISSUE THREAD

**Issue by MenacingPerson** [LimeShulkerBox/better-sodium-video-settings#7]
Would be nice to have github actions just for the sake of it

**Comment by piemanau** [comment]
I am not sure what that is sorry.

**Comment by MenacingPerson** [comment]
![image](https://user-images.githubusercontent.com/59611020/131241855-01bd8a16-5549-414b-b157-e09bbaf3de80.png)
The actions tab here. It compiles the code automatically with every commit, making it easier to create new versions on curseforge/modrinth/whatever mod platform.

**Comment by MaxBr5** [comment]
Don't bother with it, just compile it yourself.

**Comment by piemanau** [comment]
Continuing conversation in the PR
