### ISSUE TITLE
incompatibility with Castom fog

### ISSUE THREAD

**Issue by ghost** [LimeShulkerBox/better-sodium-video-settings#9]
nstalling Better Sodium Video Settings Button Mod
Together with the custom fog
Causes the game to crash
other mods were not installed at that time
except sodium sodium extra custom fog Better Sodium Video Settings Button
There seems to be no problem with the first three mods.

**Comment by piemanau** [comment]
This issue arises with sodium extra and custom fog, you should not need custom frog with sodium extra as it has the same settings as custom fog (as I am aware)

**Comment by Setadokalo** [comment]
Sodium Extra has a much weaker fog configuration system than custom fog - it allows for controlling the fog end distance in chunks only, while Custom Fog allows setting both fog start and end, as well as switching to different fog modes entirely.
As for the actual incompatibility here, it seems Custom Fog and BSVSB modified the same constant in the video settings screen. I've changed Custom Fog to not require the ModifyConstant and I can push a release for that, but you'll have to change the `breaks` clause from BSVSB for it to run. (Specifically, changing it from `"custom-fog": "*"` to `"custom-fog": "<2.0.1"` will do the trick, while still preventing incompatible versions from loading together)

**Comment by piemanau** [comment]
Hey! Thanks for the report, I will change that line with the next update, need to fix stuff with sodium extra/reeses sodium settings first and I will add in the next update. I will also just do some testing with both before I will release it, have you changed the code on custom fog yet? If so I will start soon :)

**Comment by Setadokalo** [comment]
sorry for the late response - yes, the current code on github for custom fog has the fix implemented (though I haven't released it on curseforge/etc yet; I'd like to add a little more before pushing out a full release). Here's [a pre-built version with the fix.](https://github.com/LimeShulkerBox/better-sodium-video-settings/files/7298465/custom-fog-2.0.1.zip)
